- hosts: localhost
  tasks:
    - name: start an instance and Add EBS
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        security_group: "{{ security_group }}"
        network:
          assign_public_ip: true
        image_id: "{{ image_id }}"
        volumes:
            - device_name: /dev/sda1
              ebs:
                volume_size: 16
                delete_on_termination: true
        region: "{{ specific_region }}"
        state: "started"
        tags:
          Environment: "{{ tag_environment }}"